ShopSi/ShopSi/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopSi.Areas.Admin.Controllers
{
    public class HomeController : BaseController
    {
        // GET: Admin/Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

ShopSi/ShopSi/Controllers/HomeController.cs
using Models.Dao;
using Models.EF;
using ShopSi.Common;
using ShopSi.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopSi.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            var dao = new ProductDao();
            ViewBag.NewProduct = dao.GetListNewProduct(6);
            ViewBag.FeatureProduct = dao.GetListFeatureProduct(3);
            ViewBag.Title = ConfigurationManager.AppSettings["HomeTitle"];
            ViewBag.Keywords = ConfigurationManager.AppSettings["HomeKeyword"];
            ViewBag.Descriptions = ConfigurationManager.AppSettings["HomeDescriptions"];
            return View();
        }
        [ChildActionOnly]
        public PartialViewResult TopMenu()
        {
            var model = new MenuDao().GetTopMenu(2);
            return PartialView(model);
        }

        [ChildActionOnly]
        public PartialViewResult ProductCategory()
        {
            var model = new ProductTypeDao().GetProductType();

            ViewBag.ProductCate1 = new ProductTypeDao().GetProductCategory(1);
            ViewBag.ProductCate2 = new ProductTypeDao().GetProductCategory(2);
            ViewBag.ProductCate3 = new ProductTypeDao().GetProductCategory(3);
            return PartialView(model);
        }

       
        public ActionResult ProductDetail(long id)
        {
            var model = new ProductDao().GetProductDetail(id);
            return View(model);
        }

        public ActionResult Category(long cateid,int page=1,int pageSize=6)
        {
            var model = new ProductCategoryDao().GetProductCategory(cateid);
            int totalRecode = 0;
            ViewBag.ProdcutCateId = new ProductCategoryDao().GetProductCateId(cateid,ref totalRecode, page,pageSize);
            ViewBag.Total = totalRecode;
            ViewBag.Page = page;
            int maxPage = 5;
            int totalPage = 0;
            totalPage = (int)Math.Ceiling((double)totalRecode / pageSize);
            ViewBag.TotalPage = totalPage;
            ViewBag.MaxPage = maxPage;
            ViewBag.First = 1;
            ViewBag.Last = totalPage;
            ViewBag.Next = page + 1;
            ViewBag.Prev = page - 1;
            ViewBag.FeatureProduct = new ProductDao().GetListFeatureProduct(6);
            ViewBag.ProType = new ProductTypeDao().GetProductType();
            return View(model);
        }

        [ChildActionOnly]
        public PartialViewResult Header()
        {

            var cart = Session[CommonConstant.cart_session];
            var list = new List<CartItem>();
            if (cart != null)
            {
                list = (List<CartItem>)cart;
            }
        
            return PartialView(list);
        }

        public JsonResult ListName(string q)
        {
            var data = new ProductDao().GetListName(q);
            return Json(new
            {
                data=data,
                status=true
            },JsonRequestBehavior.AllowGet);
        }

        public ActionResult Search(string searching, int page = 1, int pageSize = 6)
        {
           // var model = new ProductCategoryDao().GetProductSearching(searching);
            int totalRecode = 0;
            var model = new ProductCategoryDao().GetProductSearching(searching, ref totalRecode, page, pageSize);
            ViewBag.Total = totalRecode;
            ViewBag.Page = page;
            ViewBag.Keyword = searching;
            int maxPage = 5;
            int totalPage = 0;
            totalPage = (int)Math.Ceiling((double)totalRecode / pageSize);
            ViewBag.TotalPage = totalPage;
            ViewBag.MaxPage = maxPage;
            ViewBag.First = 1;
            ViewBag.Last = totalPage;
            ViewBag.Next = page + 1;
            ViewBag.Prev = page - 1;
            ViewBag.FeatureProduct = new ProductDao().GetListFeatureProduct(6);
           
            return View(model);
        }
    }
}

ShopSi/ShopSi/Controllers/ProCategoryController.cs
using Models.Dao;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopSi.Controllers
{
    public class ProCategoryController : Controller
    {
        // GET: ProCategory
        public ActionResult Index()
        {
            return View();
        }

        [ChildActionOnly]
        public PartialViewResult LeftMain()
        {
            var model = new ProductTypeDao().GetProductType();

            ViewBag.ProductCate1 = new ProductTypeDao().GetProductCategory(1);
            ViewBag.ProductCate2 = new ProductTypeDao().GetProductCategory(2);
            ViewBag.ProductCate3 = new ProductTypeDao().GetProductCategory(3);
            return PartialView(model);
        }
    }
}

ShopSi/ShopSi/Views/Home/Category.cshtml
@model Models.EF.Product__Category
@{
    ViewBag.Title =Model.Name;
    Layout = "~/Views/Shared/_Layout.cshtml";
    var product = (List<Models.EF.Product>)ViewBag.ProdcutCateId;
    var featureProduct = (List<Models.EF.Product>)ViewBag.FeatureProduct;
    var proType = (List<Models.EF.ProductType>)ViewBag.ProType;
}
@section jsFooter{
    <script src="/assets/client/js/cbpViewModeSwitch.js" type="text/javascript"></script>
    <script src="/assets/client/js/classie.js" type="text/javascript"></script>
    <script type="text/javascript">
					                 $(window).load(function() {
						                $("#flexiselDemo3").flexisel({
                              visibleItems: 4,
							                animationSpeed: 1000,
							                autoPlay: true,
							                autoPlaySpeed: 3000,
							                pauseOnHover: true,
							                enableResponsiveBreakpoints: true,
					    	                responsiveBreakpoints: {
                                  portrait: {
                                      changePoint:480,
					    			                visibleItems: 1

                                                },
					    		                landscape: {
                                      changePoint:640,
					    			                visibleItems: 2

                                                },
					    		                tablet: {
                                      changePoint:768,
					    			                visibleItems: 3

                                                }
                                  }
                              });

                          });
    </script>
    <script type="text/javascript" src="/assets/client/js/jquery.flexisel.js"></script>
}
<!-- content-section-starts -->
<div class="container">
    <div class="products-page">
        <div class="products">
            @{
                Html.RenderAction("LeftMain", "ProCategory");
            }
        </div>
        <div class="new-product">
            <div class="new-product-top">
                <ul class="product-top-list">
                    <li><a href="/">Home</a>&nbsp;<span>&gt;</span></li>
                    <li><span class="act"><a>@Model.Name</a></span>&nbsp;</li>
                </ul>
                <p class="back"><a href="/">Back to Previous</a></p>
                <div class="clearfix"></div>
            </div>
            <hr />
            <div id="cbp-vm" class="cbp-vm-switcher cbp-vm-view-grid">
                <div class="cbp-vm-options">
                    <a href="#" class="cbp-vm-icon cbp-vm-grid cbp-vm-selected" data-view="cbp-vm-view-grid" title="grid">Grid View</a>
                    <a href="#" class="cbp-vm-icon cbp-vm-list" data-view="cbp-vm-view-list" title="list">List View</a>
                </div>
                @*<div class="pages">
                        <div class="limiter visible-desktop">
                            <label>Show</label>
                            <select>
                                <option value="" selected="selected">
                                    9
                                </option>
                                <option value="">
                                    15
                                </option>
                                <option value="">
                                    30
                                </option>
                            </select> per page
                        </div>
                    </div>*@
                <div class="clearfix"></div>
                <ul>
                    @foreach (var item in product)
                    {
                        <li>
                            <div class="simpleCart_shelfItem">
                                <a class="cbp-vm-image" href="/chi-tiet/@item.MetaTitle-@item.ID">
                                    <div class="view view-first">
                                        <div class="inner_content clearfix">
                                            <div class="product_image">
                                                <img src="@item.Image" class="img-responsive" alt="" />
                                                <div class="mask">
                                                    <p>Xem chi tiết</p>
                                                </div>
                                                <div class="product_container">
                                                    <div class="cart-left">
                                                        <p class="title">@item.Name</p>
                                                    </div>
                                                    <div class="pricey"><span class="item_price">@item.Price ₫</span></div>
                                                    <div class="clearfix"></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </a>
                                <div class="cbp-vm-details">
                                    @item.Description
                                </div>
                                <a class="cbp-vm-icon cbp-vm-add item_add" href="/them-gio-hang?productID=@item.ID&quantity=1">Thêm vào giỏ hàng</a>
                            </div>
                        </li>
                    }
                </ul>
            </div>
            @*//Phan trang*@

            <!--Phân trang-->
            @if (ViewBag.TotalPage > 1)
            {
                var pageDisplay = (int)ViewBag.MaxPage;
                int totalPage = (int)ViewBag.TotalPage;
                int currentPage = (int)ViewBag.Page;

                // Create numeric links
                var startPageIndex = Math.Max(1, currentPage - pageDisplay / 2);
                var endPageIndex = Math.Min(totalPage, currentPage + pageDisplay / 2);
                var title = "ao/";

                if (Model.TypeID == 1)
                {
                    title = "ao/";
                }
                else if (Model.TypeID == 2)
                {
                    title = "quan/";
                }
                else
                {
                    title = "phu-kien/";
                }

                var link = "/san-pham/" + title + Model.MetaTitle + "-" + Model.ID;
                <nav>
                    <ul class="pagination">
                        @if (currentPage > ViewBag.First)
                        {
                            <li>
                                <a href="@link?page=@ViewBag.First" title="Trang đầu" class="first"><i class="fa fa-angle-double-left"></i></a>
                            </li>
                                <li>
                                    <a href="@link?page=@ViewBag.Prev" title="Trang trước" class="prev"><i class="fa fa-angle-left"></i></a>
                                </li>

                        }
                        @for (int i = startPageIndex; i <= endPageIndex; i++)
                        {
                            if (currentPage == i)
                            {

                                <li> <a href="@link?page=@i" class="active" title="Trang @i">@i</a></li>
                            }
                            else
                            {
                                <li><a href="@link?page=@i" title="Trang @i" class="pos">@i</a></li>
                            }
                        }
                        @if (currentPage < totalPage)
                        {
                            <li><a href="@link?page=@ViewBag.Next" class="next" title="Trang sau"><i class="fa fa-angle-right"></i></a></li>
                                <li> <a href="@link?page=@ViewBag.Last" class="last" title="Trang cuối"><i class="fa fa-angle-double-right"></i></a></li>
                        }

                    </ul>
                </nav>

            }
            else
            {
                <span>Không có bản ghi nào</span>
            }




            <script src="/assets/client/js/cbpViewModeSwitch.js" type="text/javascript"></script>
            <script src="/assets/client/js/classie.js" type="text/javascript"></script>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>
</div>
<!-- content-section-ends -->
<div class="other-products">
    <div class="container">
        <h3 class="like text-center">Sản phẩm nổi bật</h3>
        <ul id="flexiselDemo3">
            @foreach (var item in featureProduct)
            {
                <li>
                    <a href="/chi-tiet/@item.MetaTitle-@item.ID"><img src="@item.Image" class="img-responsive" /></a>
                    <div class="product liked-product simpleCart_shelfItem">
                        <a class="like_name" href="/chi-tiet/@item.MetaTitle-@item.ID">@item.Name</a>
                        <p><a class="item_add" href="#"><i></i> <span class="item_price">@item.Price</span></a></p>
                    </div>
                </li>
            }

        </ul>

    </div>
</div>
<!-- content-section-ends-here -->

ShopSi/ShopSi/Views/Home/Header.cshtml
@model List<ShopSi.Models.CartItem>
 @{
     decimal total = 0;
     int quantity = 0;
}

 @foreach (var item in Model)
 {
     quantity += item.Quantity;
     total += item.Product.Price.GetValueOrDefault(0) * item.Quantity;

 }


    
        <h5 style="color:white"> <img src="/assets/client/images/bag.png" alt="" />
            <a style="color:white" href="/gio-hang">
                Giỏ hàng:
                @total đ (@quantity)
            </a>
         </h5>      
   
    
    <div class="clearfix"> </div>

ShopSi/ShopSi/Views/Home/Index.cshtml
@{
   
    Layout = "~/Views/Shared/_Layout.cshtml";
    var newProduct = (List<Models.EF.Product>)ViewBag.NewProduct;
    var featureProduct = (List<Models.EF.Product>)ViewBag.FeatureProduct;
}

<div class="banner" style="background:url('/assets/client/images/banner_img.jpg') no-repeat 0px 0px">
    <div class="container">
        <div class="banner-bottom">
            <div class="banner-bottom-left">
                <h2>B<br>U<br>Y</h2>
            </div>
            <div class="banner-bottom-right">       
                     
                            <div class="banner-info">
                                <div class="shop">
                                    <h3 style="color:#816263">Shop Si</h3>
                                    <br />
                                    <a href="#"style="color:#816263">SHOP COLLECTION NOW</a>
                                </div>       
                            </div>                   
                       
            </div>
            <div class="clearfix"> </div>
        </div>
        
    </div>
</div>
<!-- content-section-starts-here -->
<div class="container">
    <div class="main-content">
        <div class="online-strip">
            <div class="col-md-4 follow-us">
                <h3>Theo dõi chung tôi : <a class="twitter" href="#"></a><a class="facebook" href="https://www.facebook.com/luanspk"></a></h3>
            </div>
            <div class="col-md-4 shipping-grid">
                <div class="shipping">
                    <img src="/assets/client/images/shipping.png" alt="" />
                </div>
                <div class="shipping-text">
                    <h3>Miễn phí Ship</h3>
                    <p style="color:#816263">Hóa đơn trên 500 ngàn</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="col-md-4 online-order">
                <p style="color:#816263">Đặt hàng online</p>
                <h3>Tel:0896-49-50-86</h3>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="products-grid">
            <header>
                <h3 class="head text-center">Sản phẩm mới nhất</h3>
            </header>
            @foreach (var item in newProduct)
            {
                <div class="col-md-4 product simpleCart_shelfItem text-center">
                    <a href="/chi-tiet/@item.MetaTitle-@item.ID "><img src="@item.Image" alt="" /></a>
                    <div class="mask">
                        <a href="/chi-tiet/@item.MetaTitle-@item.ID">Xem chi tiết</a>
                    </div>
                    <a class="product_name" href="/chi-tiet/@item.MetaTitle-@item.ID">@item.Name</a>
                    <p><a class="item_add" href="/them-gio-hang?productID=@item.ID&quantity=1"><i></i> <span class="item_price">@item.Price</span></a></p>
                </div>
               
            }     
            <div class="clearfix"></div>    
           
        </div>

        <div class="products-grid">
            <header>
                <h3 class="head text-center">Sản phẩm nổi bật</h3>
            </header>
            @foreach (var item in featureProduct)
            {
                <div class="col-md-4 product simpleCart_shelfItem text-center">
                    <a href="/chi-tiet/@item.MetaTitle-@item.ID"><img src="@item.Image" alt="" /></a>
                    <div class="mask">
                        <a href="/chi-tiet/@item.MetaTitle-@item.ID">Xem chi tiết</a>
                    </div>
                    <a class="product_name" href="/chi-tiet/@item.MetaTitle-@item.ID">@item.Name</a>
                    <p><a class="item_add" href="/them-gio-hang?productID=@item.ID&quantity=1"><i></i> <span class="item_price">@item.Price</span></a></p>
                </div>

            }
            <div class="clearfix"></div>

        </div>

    </div>

</div>

ShopSi/ShopSi/Views/Home/Search.cshtml
@model List<Models.EF.Product>
@{
        ViewBag.Title = "Search";
        Layout = "~/Views/Shared/_Layout.cshtml";
        var featureProduct = (List<Models.EF.Product>)ViewBag.FeatureProduct;
 }
    @section jsFooter{
    <script src="/assets/client/js/cbpViewModeSwitch.js" type="text/javascript"></script>
    <script src="/assets/client/js/classie.js" type="text/javascript"></script>
    <script type="text/javascript">
					                 $(window).load(function() {
						                $("#flexiselDemo3").flexisel({
                              visibleItems: 4,
							                animationSpeed: 1000,
							                autoPlay: true,
							                autoPlaySpeed: 3000,
							                pauseOnHover: true,
							                enableResponsiveBreakpoints: true,
					    	                responsiveBreakpoints: {
                                  portrait: {
                                      changePoint:480,
					    			                visibleItems: 1

                                                },
					    		                landscape: {
                                      changePoint:640,
					    			                visibleItems: 2

                                                },
					    		                tablet: {
                                      changePoint:768,
					    			                visibleItems: 3

                                                }
                                  }
                              });

                          });
    </script>
    <script type="text/javascript" src="/assets/client/js/jquery.flexisel.js"></script>
}
<!-- content-section-starts -->
<div class="container">
    <div class="products-page">
        <div class="products">
            @{
                Html.RenderAction("LeftMain", "ProCategory");
            }
        </div>
        <div class="new-product">
            <div class="new-product-top">
                <ul class="product-top-list">
                    <li><a href="/">Home</a>&nbsp;<span>&gt;</span></li>
                    <li><span class="act"><a>Kết quả tìm kiếm: @ViewBag.Keyword</a></span>&nbsp;</li>
                </ul>
                <p class="back"><a href="/">Back to Previous</a></p>
                <div class="clearfix"></div>
            </div>
            <hr />
            <div id="cbp-vm" class="cbp-vm-switcher cbp-vm-view-grid">
                <div class="cbp-vm-options">
                    <a href="#" class="cbp-vm-icon cbp-vm-grid cbp-vm-selected" data-view="cbp-vm-view-grid" title="grid">Grid View</a>
                    <a href="#" class="cbp-vm-icon cbp-vm-list" data-view="cbp-vm-view-list" title="list">List View</a>
                </div>
              
                <div class="clearfix"></div>
                <ul>
                    @foreach (var item in Model)
                    {
                        <li>
                            <div class="simpleCart_shelfItem">
                                <a class="cbp-vm-image" href="/chi-tiet/@item.MetaTitle-@item.ID">
                                    <div class="view view-first">
                                        <div class="inner_content clearfix">
                                            <div class="product_image">
                                                <img src="@item.Image" class="img-responsive" alt="" />
                                                <div class="mask">
                                                    <p>Xem chi tiết</p>
                                                </div>
                                                <div class="product_container">
                                                    <div class="cart-left">
                                                        <p class="title">@item.Name</p>
                                                    </div>
                                                    <div class="pricey"><span class="item_price">@item.Price ₫</span></div>
                                                    <div class="clearfix"></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </a>
                                <div class="cbp-vm-details">
                                    @item.Description
                                </div>
                                <a class="cbp-vm-icon cbp-vm-add item_add" href="/them-gio-hang?productID=@item.ID&quantity=1">Thêm vào giỏ hàng</a>
                            </div>
                        </li>
                    }
                </ul>
            </div>
            @*//Phan trang*@

            <!--Phân trang-->
            @if (ViewBag.TotalPage > 1)
            {
                var pageDisplay = (int)ViewBag.MaxPage;
                int totalPage = (int)ViewBag.TotalPage;
                int currentPage = (int)ViewBag.Page;

                // Create numeric links
                var startPageIndex = Math.Max(1, currentPage - pageDisplay / 2);
                var endPageIndex = Math.Min(totalPage, currentPage + pageDisplay / 2);

                var link = "/tim-kiem?searching=" + ViewBag.Keyword;
                <nav>
                    <ul class="pagination">
                        @if (currentPage > ViewBag.First)
                        {
                            <li>
                                <a href="@link&page=@ViewBag.First" title="Trang đầu" class="first"><i class="fa fa-angle-double-left"></i></a>
                            </li>
                            <li>
                                <a href="@link&page=@ViewBag.Prev" title="Trang trước" class="prev"><i class="fa fa-angle-left"></i></a>
                            </li>

                        }
                        @for (int i = startPageIndex; i <= endPageIndex; i++)
                        {
                            if (currentPage == i)
                            {

                                <li> <a href="@link&page=@i" class="active" title="Trang @i">@i</a></li>
                            }
                            else
                            {
                                <li><a href="@link&page=@i" title="Trang @i" class="pos">@i</a></li>
                            }
                        }
                        @if (currentPage < totalPage)
                        {
                            <li><a href="@link&page=@ViewBag.Next" class="next" title="Trang sau"><i class="fa fa-angle-right"></i></a></li>
                            <li> <a href="@link&page=@ViewBag.Last" class="last" title="Trang cuối"><i class="fa fa-angle-double-right"></i></a></li>
                        }

                    </ul>
                </nav>

            }
            else
            {
                <span>Không có bản ghi nào</span>
            }




            <script src="/assets/client/js/cbpViewModeSwitch.js" type="text/javascript"></script>
            <script src="/assets/client/js/classie.js" type="text/javascript"></script>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>
</div>
<!-- content-section-ends -->
<div class="other-products">
    <div class="container">
        <h3 class="like text-center">Sản phẩm nổi bật</h3>
        <ul id="flexiselDemo3">
            @foreach (var item in featureProduct)
            {
                <li>
                    <a href="/chi-tiet/@item.MetaTitle-@item.ID"><img src="@item.Image" class="img-responsive" /></a>
                    <div class="product liked-product simpleCart_shelfItem">
                        <a class="like_name" href="/chi-tiet/@item.MetaTitle-@item.ID">@item.Name</a>
                        <p><a class="item_add" href="#"><i></i> <span class="item_price">@item.Price</span></a></p>
                    </div>
                </li>
            }

        </ul>

    </div>
</div>
<!-- content-section-ends-here -->